# config.yaml
kmeans_clusters: 2
predefined_k: 2
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/prints/dataset/block/OK.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/1.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/2.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/3.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/4.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/5.jpg"
