# config.yaml
kmeans_clusters: 2
predefined_k: 2
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/prints/output/datasets/block/inputs/reference.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/block/inputs/test_images/block1.jpg"
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/block/inputs/test_images/block2.jpg"
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/block/inputs/test_images/block3.jpg"
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/block/inputs/test_images/block4.jpg"
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/block/inputs/test_images/block5.jpg"
