# config.yaml
kmeans_clusters: 2
predefined_k: 2
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/prints/dataset/block/reference.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/block1.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/block2.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/block3.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/block4.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/block/block5.jpg"

# DBN Eğitim Parametreleri
dbn_params:
  hidden_layers: [100, 50, 25]
  dropout_rate: 0.1
  batch_normalization: true
  activation: "relu"

# PSO Eğitim Parametreleri
pso_params:
  swarmsize: 20
  maxiter: 50 # Deneme için 50 iyidir, gerçek sonuç için 100+ yapabilirsiniz
  w: 0.7
  c1: 2.0
  c2: 2.0

# Genel Eğitim Parametreleri
training_params:
  n_samples: 800
  test_size: 0.2
  pso_retries: 3
