# config.yaml
kmeans_clusters: 5
predefined_k: 5
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/prints/dataset/flowers/orginal.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/prints/dataset/flowers/1.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/flowers/2.jpg"
