kmeans_clusters: 3
predefined_k: 3
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/189-orijinal.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/789-1.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/378-2.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/439-3.jpg"
