kmeans_clusters: 3
predefined_k: 3
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/prints/output/datasets/stripes/inputs/reference.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/stripes/inputs/test_images/stripes1.jpg"
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/stripes/inputs/test_images/stripes2.jpg"
  - "C:/Users/LENOVO/Desktop/prints/output/datasets/stripes/inputs/test_images/stripes3.jpg"
