kmeans_clusters: 6
predefined_k: 6
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/prints/dataset/unicorn/orginal.95.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/prints/dataset/unicorn/7-2.jpg"
  - "C:/Users/LENOVO/Desktop/prints/dataset/unicorn/60-1.jpg"
