reference_image_path: "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/1/1/orginal.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/1/1/1.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/1/1/2.jpg"
distance_threshold: 20
kmeans_clusters: 5
preprocessing:
  geometric_transform: true
  denoising: true
  morphological_operations: true
  bilateral_filtering: true
output_dir: 'output'
