reference_image_path: "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/189-orijinal.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/789-1.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/378-2.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/3/439-3.jpg"

distance_threshold: 20
kmeans_clusters: 3
preprocessing:
  geometric_transform: true
  denoising: true
  morphological_operations: true
  bilateral_filtering: true
output_dir: 'output'
