reference_image_path: "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/2/orginal.95.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/2/7-2.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/zorlutekstil_1_2024-01-19_1042/2/60-1.jpg"

distance_threshold: 20
kmeans_clusters: 6
preprocessing:
  geometric_transform: true
  denoising: true
  morphological_operations: true
  bilateral_filtering: true
output_dir: 'output'
