# config.yaml
kmeans_clusters: 2
predefined_k: 2
distance_threshold: 0.7
reference_image_path: "C:/Users/LENOVO/Desktop/Thesis/wetransfer_jpg_2024-04-02_1007/OK.jpg"
test_images:
  - "C:/Users/LENOVO/Desktop/Thesis/wetransfer_jpg_2024-04-02_1007/1.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/wetransfer_jpg_2024-04-02_1007/2.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/wetransfer_jpg_2024-04-02_1007/3.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/wetransfer_jpg_2024-04-02_1007/4.jpg"
  - "C:/Users/LENOVO/Desktop/Thesis/wetransfer_jpg_2024-04-02_1007/5.jpg"
